### ISSUE TITLE
Crash when world loading

### ISSUE THREAD

**Issue by Dark-Peace** [x3rmination/x3dungeons#1]
Version : Minecraft 1.16.5 Forge 36.2.39 x3Dungeons 1.4
I also have a modpack with 100+ mods, I just tried to add this one

Can't enter the world, apparently someone else got that problem
Tell me if you need more infos.
Crash report :
[crash-2022-10-19_17.24.30-server.txt](https://github.com/x3rmination/x3dungeons/files/9821896/crash-2022-10-19_17.24.30-server.txt)

**Comment by x3rdev** [comment]
Please update to the newest version of the mod, if this issue persists send a new log.
